FROM andreysenov/firebase-tools
ENV HOME=/home/node
COPY test-requirements.txt .
USER root
RUN apt update -y && \
    apt install -y python3-pip
USER node
RUN pip3 install --break-system-packages --no-cache-dir -r test-requirements.txt

WORKDIR /home/node
COPY firebase.json .
COPY flask_firebaseauth.py .
COPY test_firebaseauth.py .
CMD ["firebase", "emulators:exec", "--project",  "test", "python3 -m unittest test_firebaseauth"]
